spring:
  datasource:
    url: jdbc:mysql:${APP_MYSQL_DNS_SERVER}:${APP_MYSQL_PORT}/${APP_MYSQL_DB}
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
